import Head from "next/head";
import Image from "next/image";
import Header from "../components/header";
import { Inter } from "@next/font/google";
import {
  Box,
  Button,
  Center,
  Container,
  FormControl,
  FormHelperText,
  FormLabel,
  Heading,
  HStack,
  Input,
  VStack,
} from "@chakra-ui/react";
import { useState } from "react";
import { NextPage } from "next/types";

const inter = Inter({ subsets: ["latin"] });

const Home: NextPage = () => {
  const [city, setCity] = useState("");
  const [err, setErr] = useState(false);
  const [weatherData, setWeatherdata] = useState(undefined);

  const getWeather = async (city: string) => {
    try {
      const response = await fetch(
        `http://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_OPEN_WEATHER_API_KEY}&units=imperial`
      );
      const data = await response.json();
      console.log("!@#", data);
      setWeatherdata(data);
    } catch (err) {
      console.log(err);
    }
  };
  return (
    <>
      <Head>
        <title>Best Weather App Ever</title>
        <meta
          name="The ultimate weather app by Phill Aelony! Created with NextJS 13, typescript, mobx-state tree, and ChakraUI!"
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container maxW="2xl" centerContent p={10} borderRadius={10}>
          <VStack spacing={10}>
            <FormControl>
              <HStack spacing={4}>
                <Input
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                  variant="flushed"
                  type="text"
                  placeholder="Search for a city!"
                />
                <Button onClick={() => getWeather(city)}>Search</Button>
              </HStack>
            </FormControl>
            <Box minH={8}>
              <Heading as="h2" fontSize="5xl">
                {weatherData && weatherData.main.temp}
              </Heading>
            </Box>
            <Box padding="4" maxW="md" borderRadius={10}>
              Here is where you're weather data will go
            </Box>
          </VStack>
        </Container>
      </main>
    </>
  );
};

export default Home;
